
===ID===

### id.auth
POST http://localhost:8001/auth
Content-Type: application/json

{
  "login": "vasya",
  "password": "password"
}

> {% client.global.set("token", response.body.token); %}

### auth.verify
POST http://localhost:8001/auth/verify
X-Token: rzl00lRt66/pTUrCCYSeRdzRaQKfz9ZZV5q63NIafNy4Wn6YvsekXRHeqIXJst+5nQn+HU1iWE0E/PoZ
Content-Type: application/json

{
  "token": "{{token}}"
}

===CATALOG===

### services.getAll
GET http://localhost:8002/services
X-Token: {{token}}

### stations.getAll
GET http://localhost:8002/stations
X-Token: {{token}}

### stations.getById
GET http://localhost:8002/stations/1
X-Token: {{token}}

### services.getById
GET http://localhost:8002/services/1
X-Token: {{token}}

### services.create
POST http://localhost:8002/services
X-Token: {{token}}
Content-Type: application/json

{
  "name": "Вид работ 3"
}

### stations.create
POST http://localhost:8002/stations
X-Token: {{token}}
Content-Type: application/json

{
  "name": "Название сервиса 4",
  "serviceIds": [1, 2, 3]
}

### stations.update
PUT http://localhost:8002/stations/6
X-Token: {{token}}
Content-Type: application/json

{
  "name": "Название СТО",
  "serviceSIds": [5, 2, 3]
}

### services.deleteById
DELETE http://localhost:8002/services/1
X-Token: {{token}}

### stations.deleteById
DELETE http://localhost:8002/stations/1
X-Token: {{token}}


===PLANNER===

### planner.getAll
GET http://localhost:8003/planner?stationId=1&start=2661806800&finish=2765863343
X-Token: {{token}}

### planner.getById
GET http://localhost:8003/planner/2
X-Token: {{token}}

### planner.create
POST http://localhost:8003/planner
X-Token: {{token}}
Content-Type: application/json

{
  "id": 0,
  "user": {
    "id": 1,
    "name": "Vasya"
  },
  "station": {
    "id": 1,
    "name": "гараж"
  },
  "time": 1671806800,
  "serviceIds": [1, 2],
  "status": "забронирован"
}

### planner.addService
POST http://localhost:8003/planner/1/services
X-Token: {{token}}
Content-Type: application/json

{
  "id": 0,
  "serviceId": 1
}

### planner.removeService
DELETE http://localhost:8003/planner/1/services/1
X-Token: {{token}}

### planner.deleteById
DELETE http://localhost:8003/planner/1
X-Token: {{token}}

===ORDERS===


### orders.getAll конкретной СТО
GET http://localhost:8004/orders?stationId=2&start=1661806800&finish=1665863343
X-Token: {{token}}

### orders.getById
GET http://localhost:8004/orders/2
X-Token: {{token}}

### orders.create
POST http://localhost:8004/orders
X-Token: {{token}}
Content-Type: application/json

{
  "id": 0,
  "user": {
    "id": 1,
    "name": "Vasya"
  },
  "station": {
    "id": 1,
    "name": "гараж"
  },
  "serviceIds": [1, 2],
  "status": "заброннирован"
}

### orders.addPosition
POST http://localhost:8004/orders/1/positions
X-Token: {{token}}
Content-Type: application/json

{
  "id": 0,
  "serviceId": 1,
  "price": 40000
}

### orders.removePosition

DELETE http://localhost:8004/orders/1/positions/1
X-Token: {{token}}

### orders.finishByid
PUT http://localhost:8004/orders/1
X-Token: {{token}}

### orders.deleteById
DELETE http://localhost:8004/orders/1
X-Token: {{token}}